cleantech/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('all-posts/', views.blog, name='allposts'),
    path('post/post-new', views.post_new, name="post_new"),
    path('category/<slug:category_slug>/', views.blog_as_category, name='blog_as_category'),
    path('post/<slug:post_slug>', views.post_detail, name='post_detail'),
    path('post/update/<int:pk>/', views.post_update, name='post_update'),
    path('post/delete/<int:pk>/', views.post_delete, name='post_delete'),
    path('search/', views.SearchView.as_view(), name="search"),
]

cleantech/cleantech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('tutorial/', include('tutorial.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cleantech/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.utils import timezone
from ckeditor.fields import RichTextField


def unique_slug(instance, slug):
    model = instance.__class__
    unique_slug = slug
    counter = 1
    while model.objects.filter(slug=unique_slug).exists():
        unique_slug = slugify(slug + str(counter))
        counter += 1

    return unique_slug


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=60, unique=True, editable=False)

    def __str__(self):
        return self.name

    # This save method is overriding save method!
    def save(self, *args, **kwargs) -> None:

        self.slug = unique_slug(self, slugify(self.name))
        super().save(*args, **kwargs)


class Post(models.Model):
    author = models.ForeignKey(User, null=False, on_delete=models.CASCADE, verbose_name='Author')
    title = models.CharField(max_length=200, verbose_name='Title')
    content = RichTextField(blank=True, null=True, verbose_name='Content')
    published_date = models.DateTimeField(default=timezone.now, editable=False)
    last_update = models.DateTimeField(null=True, blank=True, editable=False)
    image = models.ImageField(upload_to='images/blog/%Y/%m/%d/', blank=True, default='images/blog/default_post_image.jpg')
    is_available = models.BooleanField(default=True, verbose_name='Is Available')
    categories = models.ManyToManyField(Category, blank=True, verbose_name='Categories')
    slug = models.SlugField(unique=True, editable=False)


    # This save method is overriding save method!
    def save(self, *args, **kwargs) -> None:
        
        self.last_update = timezone.now()
        self.slug = unique_slug(self, slugify(self.title))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

cleantech/pages/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Name',
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Your Email',
    }))
    subject = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Subject',
        'max_length': 150,
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Your Message',
        'rows': '6',
    }))

    class Meta:
        model = Contact
        fields =  ['name', 'email','subject', 'message']

cleantech/templates/pages/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %} About {% endblock %}



{% block content %}


<br>
<div class="bg-dark text-secondary px-3 py-4 text-center my-2">
  <div class="py-5">
    <h1 id="blog-title" class="display-5 fw-bold text-white">About Us</h1>
    <div class="col-lg-6 mx-auto">
      <p class="fs-5 mb-4"></p>
    </div>
  </div>
</div>

<div class="container my-4">

  <div class="row">

    <div class="col-lg-3"></div>
    <div class="col-lg-5 mx-auto ">
      <h2>Who We Are?</h2>
      <p>Cleantecharticles.com is a small site that contains too many articles about software technologies and English Language with basic
        English to more understandable around the world.</p>
      <br>
      <hr>
      <h2>What You Will Find in This Site?</h2>
      <p>You will find
        Python program examples with their explanation.
        General python subject articles such as classes, decorators or basic python for novice visitors.
        English learning articles such as weather or verbs or English grammars.
        CMD and windows articles.
        on this site.</p>
      <br>
      <hr>
      <p class="bg-info p-2 text-dark rounded">Note: All articles under control to avoid wrong info.</p>
    </div>
    <div class="col-lg-3"></div>
  </div>

</div>

<div class="bg-dark text-secondary px-4 py-5 text-center mt-2">
  <div class="py-5">
    <h1 class="display-5 fw-bold text-white">{{ home_content.social_sec_title|title }}</h1>
    <div class="col-lg-6 mx-auto">
      <p class="fs-5 mb-4">{{ home_content.social_sec_description }}</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <a class="btn btn-outline-info btn-lg btn-floating" href="{{ home_content.instagram_url }}" target='_blank'
          role="button"><i class="fa fa-instagram"></i></a>
        <a class="btn btn-outline-warning btn-lg btn-floating" href="{{ home_content.github_url }}" target='_blank'
          role="button"><i class="fa fa-github"></i></a>

        <a class="btn btn-outline-primary btn-lg btn-floating" href="{{ home_content.twitter_url }}" target='_blank'
          role="button"><i class="fa fa-twitter"></i></a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

cleantech/templates/pages/contact.html
{% extends 'base.html' %}

{% block title %} Contact {% endblock %}

{% block content %}

<br>
    <div class="bg-dark text-secondary px-3 py-4 text-center my-2">
        <div class="py-5">
            <h1 class="display-5 fw-bold text-white">Contact Us</h1>
            <div class="col-lg-6 mx-auto">
                <p class="fs-5 mb-4"></p>
            </div>
        </div>
    </div>
    <!-- Wrapper container -->
    <div class="container py-4">

        <div class='row'>
            <div class='col-lg-3 col-md-2'>
            </div>
            <div class='col-lg-5 col-md-7 mx-auto'>

                {% if messages %}

                    {% for message in messages %}
                        {% if message.tags == 'success' %}
                            <div id='message' class="alert alert-{{message.tags}}">
                                {{message}}
                            </div>
                        {% endif %}
                    {% endfor %}

                {% endif %}
                <form id="contactForm" action="" method="POST">
                    {% csrf_token %}
                    <!-- Name input -->
                    <div class="mb-3">
                        <label class="form-label" for="id_name">Name</label>
                        {{ form.name }}
                    </div>

                    <!-- Email address input -->
                    <div class="mb-3">
                        <label class="form-label" for="id_emailAddress">Email Address</label>
                        {{ form.email }}
                    </div>

                    <!-- Subject input -->
                    <div class="mb-3">
                        <label class="form-label" for="id_subject">Subject</label>
                        {{ form.subject }}
                    </div>
                    
                    <!-- Message input -->
                    <div class="mb-3">
                        <label class="form-label" for="message">Message</label>
                        {{ form.message }}
                    </div>

                    <!-- Form submit button -->
                    <div class="d-grid">
                        <button class="btn btn-success btn-lg mx-auto" id="submitButton" type="submit">Send Message</button>
                    </div>

                </form>
            </div>
            <div class='col-lg-3 col-md-2'>
            </div>
        </div>

    </div>

{% endblock %}

cleantech/templates/pages/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home {% endblock %}

{% block content %}
    <br>
    <div class="bg-dark text-secondary px-3 py-4 text-center my-2">
        <div class="py-5">
            <h1 class="display-5 fw-bold text-white">{{ home_content.header_title }}</h1>
            <div class="col-lg-6 mx-auto">
                <p class="fs-5 mb-4">{{ home_content.header_description }}</p>
                <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                    <a class="btn btn-outline-info btn-lg px-4 me-sm-3 fw-bold" href="{% url 'allposts' %}" role="button">Visit Blog</a>
                </div>
            </div>
        </div>
    </div>

    <div class="container py-4 text-center">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-5 d-inline mt-2">
                <div class="h-100 p-3 bg-light border border-success rounded-3">
                    <div class="my-auto">
                        <h2>{{ home_content.tut1_title|title }}</h2>
                        <p>{{ home_content.tut1_description }}</p>
                        <a class="btn btn-outline-success btn-md px-4 me-sm-3 fw-bold" href="#" role="button">Go For {{ home_content.tut1_title }}</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-5 d-inline mt-2">
                <div class="h-100 p-3 bg-light border border-success rounded-3">
                    <div class="my-auto">
                        <h2 >{{ home_content.tut2_title|title }}</h2>
                        <p>{{ home_content.tut2_description }}</p>
                        <a class="btn btn-outline-success btn-md px-4 me-sm-3 fw-bold" href="#" role="button">Go For {{ home_content.tut2_title }}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container col-xxl-8 px-2 py-3">
        <div class="row flex-lg-row-reverse d-flex justify-content-center text-center g-5 py-5">
            <picture class="col-lg-6">
                <img src="{{ home_content.middle_section_img.url }}" class="rounded img-thumbnail" alt="programmer"
                loading="lazy">
            </picture>
            <div class="col-lg-6 my-auto">
                <h1 class="display-5 fw-bold lh-1 my-3">{{ home_content.middle_section_title|title }}</h1>
                <p class="lead">{{ home_content.middle_section_description }}</p>
            </div>
        </div>
    </div>

    <!-- counters starts -->
    <div class="container">
        <div class="row py-3 d-flex justify-content-center mx-auto">
            <div class="col-lg-3 text-center border border-success rounded-pill mx-2 my-2">
                <h4 class="text py-5"><i class="fa fa-pencil"></i> Authors - {{num_of_authors}}</h4>
            </div>
            <div class="col-lg-3 text-center border border-success rounded-pill mx-2 my-2">
                <h4 class="text py-5"><i class="fa fa-book"></i> Articles - 12</h4>
            </div>
            <div class="col-lg-3 text-center border border-success rounded-pill mx-2 my-2">
                <h4 class="text py-5"><i class="fa fa-eye"></i> Visited - 756</h4>
            </div>
        </div>  
    </div>
    <!--  counters ends -->

    <div class="container py-4 text-center">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-5 my-1">
                <div class="h-100 p-3 bg-light border border-success rounded-3">
                    <h2>{{ home_content.tut3_title|title }}</h2>
                    <p>{{ home_content.tut3_description }}</p>
                    <a class="btn btn-outline-success btn-md px-4 me-sm-3 fw-bold" href="{% url 'blog_as_category' 'linux' %}" role="button">Go For Linux Articles</a>
                </div>

            </div>
            <div class="col-lg-5 my-1">
                <div class="h-100 p-3 bg-light border border-success rounded-3">
                    <h2>{{ home_content.tut4_title|title }}</h2>
                    <p>{{ home_content.tut4_description }}</p>
                    <a class="btn btn-outline-success btn-md px-4 me-sm-3 fw-bold" href="{% url 'blog_as_category' 'windows' %}" role="button">Go For Windows Articles</a>
                </div>
            </div>
        </div>
    </div>


    <div class="bg-dark text-secondary px-4 py-5 text-center mt-2">
        <div class="py-5">
            <h1 class="display-5 fw-bold text-white">{{ home_content.social_sec_title|title }}</h1>
            <div class="col-lg-6 mx-auto">
                <p class="fs-5 mb-4">{{ home_content.social_sec_description }}</p>
                <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                    <a class="btn btn-outline-info btn-lg btn-floating" href="{{ home_content.instagram_url }}" target = '_blank'
                        role="button"><i class="fa fa-instagram"></i></a>
                    <a class="btn btn-outline-warning btn-lg btn-floating" href="{{ home_content.github_url }}" target = '_blank'
                        role="button"><i class="fa fa-github"></i></a>

                    <a class="btn btn-outline-primary btn-lg btn-floating" href="{{ home_content.twitter_url }}" target = '_blank'
                        role="button"><i class="fa fa-twitter"></i></a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}