cleantech/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('all-posts/', views.blog, name='allposts'),
    path('post/post-new', views.post_new, name="post_new"),
    path('category/<slug:category_slug>/', views.blog_as_category, name='blog_as_category'),
    path('post/<slug:post_slug>', views.post_detail, name='post_detail'),
    path('post/update/<int:pk>/', views.post_update, name='post_update'),
    path('post/delete/<int:pk>/', views.post_delete, name='post_delete'),
    path('search/', views.SearchView.as_view(), name="search"),
]

cleantech/cleantech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('tutorial/', include('tutorial.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cleantech/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.utils import timezone
from ckeditor.fields import RichTextField


def unique_slug(instance, slug):
    model = instance.__class__
    unique_slug = slug
    counter = 1
    while model.objects.filter(slug=unique_slug).exists():
        unique_slug = slugify(slug + str(counter))
        counter += 1

    return unique_slug


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=60, unique=True, editable=False)

    def __str__(self):
        return self.name

    # This save method is overriding save method!
    def save(self, *args, **kwargs) -> None:

        self.slug = unique_slug(self, slugify(self.name))
        super().save(*args, **kwargs)


class Post(models.Model):
    author = models.ForeignKey(User, null=False, on_delete=models.CASCADE, verbose_name='Author')
    title = models.CharField(max_length=200, verbose_name='Title')
    content = RichTextField(blank=True, null=True, verbose_name='Content')
    published_date = models.DateTimeField(default=timezone.now, editable=False)
    last_update = models.DateTimeField(null=True, blank=True, editable=False)
    image = models.ImageField(upload_to='images/blog/%Y/%m/%d/', blank=True, default='images/blog/default_post_image.jpg')
    is_available = models.BooleanField(default=True, verbose_name='Is Available')
    categories = models.ManyToManyField(Category, blank=True, verbose_name='Categories')
    slug = models.SlugField(unique=True, editable=False)


    # This save method is overriding save method!
    def save(self, *args, **kwargs) -> None:
        
        self.last_update = timezone.now()
        self.slug = unique_slug(self, slugify(self.title))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

cleantech/blog/forms.py
from django import forms
from .models import Post
from ckeditor.fields import RichTextFormField

class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.widgets.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Post Title',
    }))
    content = RichTextFormField()
    
    image = forms.ImageField(widget=forms.widgets.ClearableFileInput(attrs={
        'class':'form-control',
    }), required=False)
    is_available = forms.BooleanField(widget=forms.CheckboxInput(attrs={
        'class': 'form-check-input',
    }), required=False)

    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'is_available', 'categories']

cleantech/blog/views.py
from django.http import Http404

from django.core.paginator import Paginator

from django.shortcuts import get_object_or_404, redirect, render

from accounts.models import Profile
from django.contrib import messages
from .forms import PostForm
from .models import Post, Category
from django.contrib.auth.decorators import login_required
from django.views.generic import View


def blog(request):
    posts = Post.objects.filter(is_available=True).order_by('-published_date')
    paginator = Paginator(posts, 12)  # show 12 contact per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    categories = Category.objects.all()

    context = {
        'page_obj': page_obj,
        'categories': categories,
    }
    return render(request, 'blog/blog.html', context)


def blog_as_category(request, category_slug):
    posts = Post.objects.filter(
        is_available=True, categories__slug=category_slug).order_by('-published_date')
    paginator = Paginator(posts, 12)  # show 12 contact per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    categories = Category.objects.all()

    context = {
        'page_obj': page_obj,
        'categories': categories,
    }
    return render(request, 'blog/blog.html', context)


def post_detail(request, post_slug):
    post = get_object_or_404(Post, is_available=True, slug=post_slug)
    context = {
        'post': post,
        'the_post_categories': post.categories.all()
    }
    return render(request, 'blog/post_detail.html', context)


@login_required
def post_update(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)

        # if form.has_changed():
        #     print('Some changes has occourd!')

        if form.is_valid():

            post = form.save(commit=False)
            post.author = request.user
            post.categories.set(form.cleaned_data['categories'])
            post.save()

            # if author make deactivate the post
            if post.is_available == False:
                return redirect('my-posts', username=request.user.username)
            else:
                return redirect('post_detail_dashboard', username=request.user.username, post_slug=post.slug)
    #categories = Category.objects.all()
    else:
        form = PostForm(instance=post)
    context = {
        'form': form,
        'post': post,
    }
    return render(request, 'blog/post_update.html', context)


def post_new(request):
    if Profile.objects.get(user=request.user).user_type == 'blog_author':
        if request.method == 'POST':
            form = PostForm(request.POST, files=request.FILES)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.save()
                post.categories.set(form.cleaned_data['categories'])
                # This is(categories) adding after saveing beacuse this needs post id!

                if post.is_available == False:
                    return redirect('my-drafts', username=request.user.username)
                else:
                    return redirect('post_detail_dashboard', username=request.user.username, post_slug=post.slug)
        else:
            print('else')
            form = PostForm()
        context = {
            'form': form,
        }
        return render(request, 'blog/post_new.html', context)
    else:
        # TODO add message to the user
        return redirect('allposts')


def post_delete(request, pk):
    current_user = request.user
    post = Post.objects.get(id=pk)
    post_title: str = post.title
    if current_user.id == post.author.id:  # if current user and post author is same person
        post.delete()
        messages.success(
            request, f'\"{post_title.capitalize()}\" has been deleted!')
        return redirect('my-posts', username=current_user.username)
    else:
        messages.warning(
            request, f'{post_title.capitalize()} has not been deleted!')
        return redirect('allposts')

from django.http import JsonResponse
from django.core import serializers


class SearchView(View):

    def get(self, request):
        # Add here more filter to security or search on net !
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            searchbox_text = request.GET.get('searchbox_text')
            if searchbox_text == "" or len(searchbox_text) > 200:
                search_results = False
            else:
                #TODO Do not send all object data just send title and slug field!
                search_results = Post.objects.filter(is_available=True, title__contains=str(searchbox_text))[:20]
            if search_results and search_results.count() >= 1:  
                search_results = serializers.serialize('json', search_results)
            else:
                search_results = False # list(search_results)
            return JsonResponse({'search_results': search_results}, status=200)

        else:
            raise Http404

cleantech/templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %} Blog {% endblock title %}

{% block style %}

    .input-icons i {
        position: absolute;
    }
      
    .input-icons {
        width: 100%;
        margin-bottom: 10px;
    }
      
    .icon {
        padding: 10px;
        min-width: 40px;
    }
      
    .input-field {
        width: 100%;
        padding: 10px;
        text-align: center;
    }

{% endblock  %}

{% block content %}


    <br>
    <div class="bg-dark text-secondary px-3 py-4 text-center my-2" id="blogheader">
        <div class="py-5">
            <h1 id="blog-title" class="display-5 fw-bold text-white">Blog</h1>
            <div class="col-lg-6 mx-auto">
                <p class="fs-5 mb-4"></p>
            </div>
        </div>
    </div>
    <div class="container px-5">
        <div class="row d-flex justify-content-center ">

            <div class="col-lg-3 my-3 d-inline">
                <form action="#" class="d-flex" method="GET" autocomplete="off">
                    <div class="input-icons">
                        <i class="bi bi-search icon"></i> 
                        <input class="input-text form-control me-2 input-field" type="text" id="searchbox" placeholder="Find on CTA" name="search" maxlength="200">
                    </div>
                  </form>
                    <div class="mb-3 mt-1 card overflow-auto" id="searchcard" data-tag="dropdown-list" style="display: none; position: absolute; z-index: 1; font-size: 14px; max-height: 160px; min-width: 240px; max-width: 560px;">
                        <div class="card-body">
                            <ul class="list-group list-group-flush rounded" id="search_results">
                                
                            </ul>
                        </div>
                    </div>
                <hr>
                <div class="card" id="categories">
                    <div class="card-header ">
                        <h5 class="text-start my-auto text-muted">Categories</h5>
                    </div>
                    <div class="card-body">
                        <ul class="list-group shadow-lg list-group-flush rounded" id="category_list" title="categories">
                            {% for category in categories %}
                                <a href="{% url 'blog_as_category' category.slug %}" class="list-group-item {% if category.slug in request.path %}active{% endif %}">{{ category.name|title }}</a>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

            
            <div class="col-lg-9 my-4">
                    {% if messages %}
                        {% for message in messages %}
                            <div id="message" class="alert alert-{{message.tags}}">
                                {{message}}
                            </div>
                        {% endfor %}
                    {% endif %}
                <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
                    {% for post in page_obj %}
                        
                        <div class="col d-flex justify-content-center">
                            
                            <div class="card" style="width: 18rem;">
                                <img src="{% if post.image %}{{ post.image.url }}{% endif %}" class="card-img-top" alt="...">
                                <div class="card-body">
                                  <h5 class="card-title">{{ post.title|title }}</h5>
                                  <a href="{% url 'post_detail' post.slug %}" class="btn btn-info btn-sm stretched-link float-end">Get Post</a>
                                </div>
                                <div class="card-footer">
                                    <small class="text-muted">{{ post.published_date|naturaltime }}</small>
                                    <small class="float-end">Author: {{ post.author|title }}</small>
                                </div>
                            </div>
                        </div>
                        
                    {% endfor %}


                </div>
            </div>

            <div class="row my-4">
                <nav>
                    <ul class="pagination justify-content-end">
                        
                            {% if page_obj.has_previous %}
                                <li class="page-item"><a href="?page=1" class="page-link">First</a></li>
                                <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; </a></li>
                            {% endif %}
                    
                            <li class="page-item">
                                <a class="page-link active text-white"  href="?page={{ page_obj.number }}"> Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
                            </li>
                    
                            {% if page_obj.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo; </a></li>
                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last </a></li>
                            {% endif %}
                        
                    </ul>
                </nav>
            </div>


        </div>
    </div>

    
{% endblock content %}

{% block custom_script %}
    {% comment %} Change blog title if slected a category. {% endcomment %}
    
    if ($("a.list-group-item").is(".active")){
        var current_category = $("a.list-group-item.active").text();
        $("#blog-title").text("Blog - " + current_category);
        $(document).prop('title', "Blog - " + current_category + " | cta")
    }


{% endblock %}

{% block js %}
    <script src="{% static 'js/search.js' %}"></script>
{% endblock  %}

cleantech/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} {{ post.title }} {% endblock  %}


{% block content %}
<br>
<br>
<div class="row my-5">
  <div class="col-lg-2"></div>
  <div class="col-lg-8 mx-3">
      <!-- card -->
      <div class="card">
        <img src="{{ post.image.url }}" style="width: 28rem;" class="card-img-top mx-auto my-3" alt="...">
        <ul class="list-group list-group-flush">
          
            <li class="list-group-item d-flex justify-content-end" style="display: block;">

              {% for category in  the_post_categories %}
                <a class="link-info" href="{% url 'blog_as_category' category.slug %}">{{ category.name }}{% if not forloop.last %}, &nbsp; {% endif %}</a>
              {% endfor %}
            </li>
          
        </ul>
        <div class="card-body">
          <h5 class="card-title">{{ post.title|title }}</h5>
          <p class="card-text">{{ post.content }}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Author: {{ post.author|upper }} {% if post.author.id == user.id %}'You'{% endif %}</li>
        </ul>
        <div class="card-body">
          {% if user.is_authenticated and post.author.id == user.id %}
            <a class="btn btn-outline-warning" href='#' type="button">Edit</a>
          {% endif %}
        </div>

      </div>
      <!-- card end -->
  </div>
  </div>
  <div class="col-lg-2"></div>
</div>


{% endblock  %}

cleantech/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} {{ post.title }} {% endblock  %}


{% block content %}

<!-- For Callout -->
<style>
  
  .callout {
    position: fixed;
    bottom: 35px;
    right: 20px;
    margin-left: 20px;
    max-width: 300px;
  }
  
  .callout-header {
    padding: 25px 15px;
    background: rgb(48, 196, 250);
    font-size: 24px;
    color: rgb(0, 0, 0);
    border-radius: 15px;
  }
  
</style>

<br>
<div class="bg-dark text-secondary px-3 py-4 text-center my-2">
  <div class="py-5">
      <h1 class="display-6 fw-bold text-white">{{post.title|title}}</h1>
      <div class="col-lg-6 mx-auto">
          <p class="mb-3">
            <div >
              <ul style="list-style-type: none;">
                <li class="" style="display: block; float: center;">Author: {{ post.author|upper }} {% if post.author.id == user.id %}'You'{% endif %}</li>
                <li class="" style="display: block; float: center;">Related Categories: &nbsp;

                  {% for category in  the_post_categories %}
                    <a class="link-info" href="{% url 'blog_as_category' category.slug %}">{{ category.name }}{% if not forloop.last %}, &nbsp; {% endif %}</a>
                  {% endfor %}
                </li>
                <li class="" style="display: block; float: center;">Published Date: {{ post.published_date|naturaltime }}</li>
              </ul>
            </div>
          </p>
      </div>
  </div>
</div>
<div class="container">
  <div class="row my-5">
    <div class="col-lg-1"></div>
    <div class="col-lg-6 px-3" style="background-color:#faf9f2; border-radius: 5px;">
        <!-- card -->
        <div class="my-3">
          <div class="row">
            <div class="col-6">
              <p class="text-secondary pt-1">{% if post.last_update %}Last Update: {{post.last_update|naturaltime}}{% else %}{{ post.published_date|naturaltime }}{% endif %}</p>
            </div>
            <div class="col-6">
              <span class="badge bg-info p-2 float-end" id="copybutton" style="cursor: pointer !important;" onclick="copyUrl();" title="Copy article url to share!"> <i class="fa fa-clipboard" aria-hidden="true"></i>&nbsp;Copy Post Link</span>
            </div>
          </div>
          <br>
          <h3 class="display-8">{{ post.title|title }}</h3>
          <hr> 
          <div class="row">
            <div class="col-2"></div>
            <div class="col-8"><img src="{% if post.image %}{{ post.image.url }}{% endif %}" style="width:100%; height:auto;" class="card-img-top mx-auto my-3" alt="..."></div>
            <div class="col-2"></div>
          </div>

          <hr>
          
          <div class="">
            <p class="">{{ post.content|safe }}</p>
          </div>

        </div>
        <!-- card end -->
        <hr>
    </div>
    </div>
    <div class="col-lg-4"></div>
  </div>
</div>

<div class="callout animate slideIn" id="callout" style="display: none;">
  <div class="alert alert-success shadow px-3">Copied to Clipboard!</div>
</div>


{% endblock  %}

{% block custom_script %}
    function copyUrl() {
      var current_url = window.location.href;
      navigator.clipboard.writeText(current_url);
      var copybutton = $("#copybutton");
      copybutton.attr("disabled", true);
      copybutton.removeClass("bg-info");
      copybutton.addClass("bg-success");
      copybutton.html('<i class="fa fa-clipboard" aria-hidden="true"></i> Copied');

      callout = $("#callout");
      callout.css("display", "block");
      setTimeout(() => {
        callout.css("display", "none");
        copybutton.html('<i class="fa fa-clipboard" aria-hidden="true"></i> Copy Post Link');
        copybutton.removeAttr("disabled");
        copybutton.removeClass("bg-success");
        copybutton.addClass("bg-info");
      }, 6000);
    }
{% endblock %}

cleantech/templates/blog/post_new.html
{% extends 'accounts/base_dashboard.html' %}

{% block title %} New Post {% endblock %}

{% block dashboard_content %}

    <div class="container my-3">
        <div class="row">
            <div class="col-lg-12">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form.as_p }}
                    <div class="mb-3 d-flex justify-content-end">
                        <button type="submit" class="btn btn-outline-success">Publish</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock  %}

{% block custom_script %}

    {% comment %} To change the title of the page base on the new post title {% endcomment %}
    
    $("#id_title").on("input", function() {
        $(document).prop('title', this.value);
    });

    {% comment %} To add bootstrap style class to categories  {% endcomment %}

    $( "#id_categories" ).addClass("form-select");

{% endblock %}

cleantech/templates/blog/post_update.html
{% extends 'accounts/base_dashboard.html' %}

{% block title %} {{ post.title }}| Update {% endblock %}

{% block dashboard_content %}

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form.as_p }}
                    <div class="mb-3 d-flex justify-content-end">
                        <button type="submit" class="btn btn-outline-success">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock  %}

{% block custom_script %}

    {% comment %} To change the title of the page base on the new post title {% endcomment %}
    
    $("#id_title").on("input", function() {
        $(document).prop('title', this.value);
    });

    {% comment %} To add bootstrap style class to categories  {% endcomment %}

    $( "#id_categories" ).addClass("form-select");

{% endblock %}